### ISSUE TITLE
Setup Deployment

### ISSUE THREAD

**Issue by namirsab** [namirsab/course-app-showcase-21-4#4]
## Value Statement
As a developer and contributor to this project
I want to see every increment deployed so its easy to test

## Description
Having the app continuously deployed makes it easier to test and release every new version. 

## Acceptance Criteria (What should I have achieved before I can consider this ticket finished). 
* [x] `main` branch should be deployed after every change.  
* [x] Every PR should have a corresponding deployment so it's easy for reviewers to check

## Tasks
As my app is just a client side application, I'm going to go with [Vercel](https://vercel.com)
* [x] Setup Vercel
* [x] Connect Vercel to this repository
    * [x] Double check the its configured properly:
         * [x]  Deployments for main branch
         * [x] Deployments for every PR

## Complexity
Small
